server:
  port: 9000
spring:
  application:
    name: based
  redis:
    database: 0
    host: 192.168.117.133
    port: 6379
    password: root

  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.21.208:3306/base?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    show-sql: false


eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.117.133:1111/eureka/
#配置开启健康检查
    healthcheck:
      enabled: true


